workflows:
  build_and_deploy:
    name: Build and Deploy to Firebase
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
      groups:
        - firebase_credentials  # 关联 Firebase 密钥
    scripts:
      - name: 获取 Flutter 依赖
        script: flutter pub get
      - name: 运行测试
        script: flutter test
      - name: 构建 Android 应用
        script: flutter build apk --release
      - name: 构建 iOS 应用（可选）
        script: flutter build ios --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      firebase:
        app_id: "my-project-ecec2"
        service_account: $FIREBASE_CREDENTIALS
        groups: testers